import type { Metadata } from "next";
import "@/styles/globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import MobileNav from "@/components/Navigation/MobileNav";
import { Providers } from "@/contexts/Providers";
import QueryProviders from "@/contexts/QueryProviders";

export const metadata: Metadata = {
  title: "책모음 - 검색",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className='flex flex-col min-h-screen w-full'>
        <AuthProvider>
          <QueryProviders>
            <Providers>{children}</Providers>
          </QueryProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
