import type { Metadata } from "next";
import "../../styles/globals.css";

export const metadata = {
  title: '로그인',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
