import type { Metadata } from "next";
import "../styles/globals.css";
import Nav from "@/components/Navigation/Nav";

export const metadata: Metadata = {
  title: "책모음",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
