import type { Metadata } from "next";
import "@/styles/globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import QueryProviders from "@/contexts/QueryProviders";

export const metadata = {
  title: "로그인",
  description: "Generated by Next.js",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <AuthProvider>
        <QueryProviders>
          <body>{children}</body>
        </QueryProviders>
      </AuthProvider>
    </html>
  );
}
