import type { Metadata } from "next";
import "../../styles/globals.css";
import Footer from "@/components/Footer";
import SearchNav from "@/components/Navigation/SearchNav";

export const metadata: Metadata = {
  title: "책모음 - 검색",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <SearchNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
