import type { Metadata } from "next";
import "@/styles/globals.css";
import Footer from "@/components/Footer";
import SearchNav from "@/components/Navigation/SearchNav";
import { AuthProvider } from "@/contexts/AuthContext";
import MobileNav from "@/components/Navigation/MobileNav";
import { Providers } from "@/contexts/Providers";

export const metadata: Metadata = {
  title: "책모음 - 검색",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className='flex flex-col min-h-screen w-full'>
        <AuthProvider>
          <SearchNav />
          <Providers>{children}</Providers>
          <Footer />
          <MobileNav />
        </AuthProvider>
      </body>
    </html>
  );
}
